//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutherAndBook
    {
        public int ID { get; set; }
        public int ID_Book { get; set; }
        public int ID_Auther { get; set; }
    
        public virtual Auther_table Auther_table { get; set; }
        public virtual Book_table Book_table { get; set; }
    }
}
