//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_table()
        {
            this.AutherAndBooks = new HashSet<AutherAndBook>();
            this.Borrows = new HashSet<Borrow>();
        }
    
        public int Book_id { get; set; }
        public string Title { get; set; }
        public int Edition { get; set; }
        public string Subject { get; set; }
        public string Descrption { get; set; }
        public string Auther_name { get; set; }
        public System.DateTime Publication_date { get; set; }
        public int publisher_ID { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutherAndBook> AutherAndBooks { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Subject_table Subject_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrow> Borrows { get; set; }
    }
}
