//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class record_history
    {
        public int Member_ID { get; set; }
        public int Rec_ID { get; set; }
        public string name { get; set; }
        public System.DateTime Enter_date { get; set; }
        public Nullable<System.DateTime> Out_date { get; set; }
        public string State { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
